name: e_halisaha
description: "E-Halısaha"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  geolocator: ^10.1.0
  http: ^1.2.0
  flutter_secure_storage: ^10.0.0
  mask_text_input_formatter: ^2.9.0
  video_player: ^2.10.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2 # Sürüm 0.18.1'den 0.20.2'ye güncellendi (Hata buradaydı)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/resimler/
    - assets/icon.png
    - assets/icon_beyaz.png
    - assets/icon_siyah.png
    - assets/video.mp4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21