name: e_halisaha
description: "E-Halısaha"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # İkon paketi buraya eklendi (Hizalamaya dikkat edildi)
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

# Flutter Ayarları
flutter:
  uses-material-design: true
  assets:
    - assets/resimler/

# İkon Oluşturma Ayarları (En sola dayalı olmalı)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21